package model

func GetCategoryByID(categoryID int) Category {
	categories := map[int]Category{
		1:  {ID: 1, ParentID: 0, CategoryName: "ソファー"},
		2:  {ID: 2, ParentID: 1, CategoryName: "一人掛けソファー"},
		3:  {ID: 3, ParentID: 1, CategoryName: "二人掛けソファー"},
		4:  {ID: 4, ParentID: 1, CategoryName: "コーナーソファー"},
		5:  {ID: 5, ParentID: 1, CategoryName: "二段ソファー"},
		6:  {ID: 6, ParentID: 1, CategoryName: "ソファーベッド"},
		10: {ID: 10, ParentID: 0, CategoryName: "家庭用チェア"},
		11: {ID: 11, ParentID: 10, CategoryName: "スツール"},
		12: {ID: 12, ParentID: 10, CategoryName: "クッションスツール"},
		13: {ID: 13, ParentID: 10, CategoryName: "ダイニングチェア"},
		14: {ID: 14, ParentID: 10, CategoryName: "リビングチェア"},
		15: {ID: 15, ParentID: 10, CategoryName: "カウンターチェア"},
		20: {ID: 20, ParentID: 0, CategoryName: "キッズチェア"},
		21: {ID: 21, ParentID: 20, CategoryName: "学習チェア"},
		22: {ID: 22, ParentID: 20, CategoryName: "ベビーソファ"},
		23: {ID: 23, ParentID: 20, CategoryName: "キッズハイチェア"},
		24: {ID: 24, ParentID: 20, CategoryName: "テーブルチェア"},
		30: {ID: 30, ParentID: 0, CategoryName: "オフィスチェア"},
		31: {ID: 31, ParentID: 30, CategoryName: "デスクチェア"},
		32: {ID: 32, ParentID: 30, CategoryName: "ビジネスチェア"},
		33: {ID: 33, ParentID: 30, CategoryName: "回転チェア"},
		34: {ID: 34, ParentID: 30, CategoryName: "リクライニングチェア"},
		35: {ID: 35, ParentID: 30, CategoryName: "投擲用椅子"},
		40: {ID: 40, ParentID: 0, CategoryName: "折りたたみ椅子"},
		41: {ID: 41, ParentID: 40, CategoryName: "パイプ椅子"},
		42: {ID: 42, ParentID: 40, CategoryName: "木製折りたたみ椅子"},
		43: {ID: 43, ParentID: 40, CategoryName: "キッチンチェア"},
		44: {ID: 44, ParentID: 40, CategoryName: "アウトドアチェア"},
		45: {ID: 45, ParentID: 40, CategoryName: "作業椅子"},
		50: {ID: 50, ParentID: 0, CategoryName: "ベンチ"},
		51: {ID: 51, ParentID: 50, CategoryName: "一人掛けベンチ"},
		52: {ID: 52, ParentID: 50, CategoryName: "二人掛けベンチ"},
		53: {ID: 53, ParentID: 50, CategoryName: "アウトドア用ベンチ"},
		54: {ID: 54, ParentID: 50, CategoryName: "収納付きベンチ"},
		55: {ID: 55, ParentID: 50, CategoryName: "背もたれ付きベンチ"},
		56: {ID: 56, ParentID: 50, CategoryName: "ベンチマーク"},
		60: {ID: 60, ParentID: 0, CategoryName: "座椅子"},
		61: {ID: 61, ParentID: 60, CategoryName: "和風座椅子"},
		62: {ID: 62, ParentID: 60, CategoryName: "高座椅子"},
		63: {ID: 63, ParentID: 60, CategoryName: "ゲーミング座椅子"},
		64: {ID: 64, ParentID: 60, CategoryName: "ロッキングチェア"},
		65: {ID: 65, ParentID: 60, CategoryName: "座布団"},
		66: {ID: 66, ParentID: 60, CategoryName: "空気椅子"},
	}
	return categories[categoryID]
}
