version: "3.8"
services:
  mysql:
    container_name: isucon9-mysql
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_HOST: "%"
      MYSQL_USER: isucari
      MYSQL_DATABASE: isucari
      MYSQL_PASSWORD: isucari
      MYSQL_ROOT_PASSWORD: isucari
    ports:
      - "3306:3306"
    volumes:
      - ./sql/00_create_database.sql:/docker-entrypoint-initdb.d/00_create_database.sql
      - ./sql/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./sql/02_categories.sql:/docker-entrypoint-initdb.d/02_categories.sql
      - ./sql/initial.sql:/docker-entrypoint-initdb.d/03_intial.sql
